### ISSUE TITLE
SoapFault exception "Internal Server Error" when using rest.afas.online as server url

### ISSUE THREAD

**Issue by Silassiai** [MegaChriz/afasprofit#11]
My following code: 
```
<?php
use Afas\Core\Server;

// Bootstrap.
require_once __DIR__ . '/vendor/autoload.php';

// Initialize server.
$server = new Server('https://***.rest.afas.online/ProfitRestServices/', '***');

// Example 1: get products from the get-connector 'Products'.
$products = $server->get('***')
    ->execute()
    ->asArray()
;
var_dump($products);
```
results in the error:
```Fatal error: Uncaught SoapFault exception: [HTTP] Internal Server Error in /Users/silasderooy/Development/MailCamp/afas-connector/vendor/megachriz/afasprofit/src/Component/Soap/SoapClient.php:18 Stack trace: #0 /Users/silasderooy/Development/MailCamp/afas-connector/vendor/megachriz/afasprofit/src/Component/Soap/SoapClient.php(18): SoapClient->__doRequest('<?xml version="...', 'https://84126.r...', 'urn:Afas.Profit...', 1, false) #1 [internal function]: Afas\Component\Soap\SoapClient->__doRequest('<?xml version="...', 'https://84126.r...', 'urn:Afas.Profit...', 1, false) #2 /Users/silasderooy/Development/MailCamp/afas-connector/vendor/megachriz/afasprofit/src/Core/Connector/ConnectorBase.php(160): SoapClient->__soapCall('GetDataWithOpti...', Array, Array) #3 /Users/silasderooy/Development/MailCamp/afas-connector/vendor/megachriz/afasprofit/src/Core/Connector/GetConnector.php(171): Afas\Core\Connector\ConnectorBase->soapSendRequest('GetDataWithOpti...', Array) #4 /Users/silasderooy/Development/MailCamp/afas-connector/vendor/megachriz/afasprofit/src/Core/Query/Get.php(139): Afas\Core\Connector\GetConnector->getData('MailCamp_2022_M...') #5 /Users/silasderooy/Development/MailCamp/afas-connector/index.php(17): Afas\Core\Query\Get->execute() #6 {main} thrown in /Users/silasderooy/Development/MailCamp/afas-connector/vendor/megachriz/afasprofit/src/Component/Soap/SoapClient.php on line 18```

**Comment by MegaChriz** [comment]
I see you are using "rest.afas.online" in the url, this should be "soap.afas.online". It should also be "profitservices" instead of "ProfitRestServices".

This library only works with the SOAP-connection that Profit provides, not the REST-one.
Example url: `https://12345.soap.afas.online/profitservices`.

**Comment by Silassiai** [comment]
Ahhhh thanks!

**Comment by MegaChriz** [comment]
🙂
