### ISSUE TITLE
UpdateConnector not working as expected

### ISSUE THREAD

**Issue by flokstra81** [MegaChriz/afasprofit#8]
I'm working on a very simple connector between our CRM and afas. 
For example, when trying to insert a KnSalesRelationPer. I'm expecting a DbId in return, but instead, get nothing. Just a dump of the object.  example output can be seen http://apiworks.makelaardijhoekstra.nl/afasTest.php
Code for this page:
`require __DIR__ . '/vendor/autoload.php';
use Afas\Core\Server;
$server = new Server('https://52886.soaptest.afas.online/ProfitServices/', 'xxxxxxxxxxxxxxxxxxxxx');
echo '<pre>';
var_dump($server->insert('KnSalesRelationPer', [
		"IsDb"=> true,
		"PaCd"=> "14",
		"CuId"=> "EUR",
		"ColA"=> "112000",
		  "KnPerson"=> [
				"PadAdr"=> true,
				"AutoNum"=> true,
				"MatchPer"=> "6",
				"SeNm"=> "345678",
				"CaNm"=> "Piet",
				"FiNm"=> "Piet Test",
				"In"=> "P. T.",
				"LaNm"=> "Tester",
				"ViGe"=> "M",
				"DaBi"=> "1981-11-17",
				"HoPa"=> "Geachte heer Tester",
				"ViMd"=> "EMA",
				"EmA2"=> "tester@testmail.com",
				"TeN2"=> "06-12345678",
			  "KnBasicAddressAdr"=> [
				"CoId"=> "NL",
				"PbAd"=> false,
				"Ad"=> "Lege Hearewei",
				"HmNr"=> 11,
				"ZpCd"=> "9054 KB",
				"Rs"=> "Hijum" 
				]
			]
		]
	)
);`

No error's nothing. Even removing the authentication token has no effect.

The GetConnector works as expected. What am I doing wrong?

**Comment by MegaChriz** [comment]
Oops, I see that I missed something in the examples and instructions. 🤭

An `insert()` or `update()` call result into a query object (\Afas\Core\Query\UpdateBaseInterface) on which you then need to call `execute()` to perform the actual query. This is something I apparently overlooked when writing the examples. Sorry for that. I'll plan to update the examples.

**Comment by flokstra81** [comment]
Thanks! Will try again

**Comment by MegaChriz** [comment]
I've updated the examples for the UpdateConnector and I added some new ones. Let me know if you understand them!

**Comment by flokstra81** [comment]
Yes, thank you very much! Going along well now!

**Comment by MegaChriz** [comment]
Alright, closing this issue :)
